# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d49ea29fc769e9c61528d9b6619ea3d185e96764a845d4ce137e7c373903c53dea95518a8bb1d5ea60671e6567b2178acf395125c1b50a74be52d51f839c15

test:
  secret_key_base: 4fda09ba8b6cb768c2219edbebce0b8de2f207383bddaeb8847ecf6ff10e25449148c9baa53cf368d3214baccad798e6c0606ed1e8b27984b07844087994f655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
